# Generated by Django 4.2.1 on 2023-10-12 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='created',
            fields=[
                ('created_on', models.DateField(auto_created=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('updated_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('created_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='channel.created')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('channel_desc', models.TextField()),
                ('poster', models.ImageField(default='', upload_to='media')),
                ('Profile_img', models.ImageField(default='', upload_to='media')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner_of_channel')),
            ],
            bases=('channel.created',),
        ),
    ]
