# Generated by Django 4.2.1 on 2023-10-12 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channel', '0002_category_channel_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('liked', models.BooleanField()),
                ('byuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topicname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='reply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('replycontent', models.CharField(max_length=300)),
                ('byuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(related_name='replylike', to='blog.like')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('commentcontent', models.CharField(max_length=300)),
                ('byuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(related_name='commentlike', to='blog.like')),
                ('reply', models.ManyToManyField(related_name='reply', to='blog.reply')),
            ],
        ),
        migrations.CreateModel(
            name='Blogposts',
            fields=[
                ('blogid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=200)),
                ('blog', models.TextField()),
                ('slug', models.CharField(max_length=300, unique=True)),
                ('mainimage', models.ImageField(default='', upload_to='')),
                ('date', models.DateField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('Channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.channel')),
                ('blogcomment', models.ManyToManyField(related_name='blogcomment', to='blog.comment')),
                ('like', models.ManyToManyField(default=None, related_name='bloglike', to='blog.like')),
                ('tag', models.ManyToManyField(default=None, related_name='topics', to='blog.topic')),
            ],
        ),
    ]
